<a href="https://colab.research.google.com/github/Shrayash-hub/Machine_Learning/blob/main/FetchingDataFromAnAPI.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

This cell imports two essential libraries:

* **`requests`**: A library for making HTTP requests to fetch data from web APIs.

In [2]:
import pandas as pd
import requests

makes an HTTP GET request to The Movie Database (TMDb) API to retrieve a list of top-rated movies. It uses:

*   **`requests.get()`**: To send the GET request.
*   **`api_key`**: Your unique API key for authentication with TMDb.
*   **`language=en-US`**: Specifies the language for the results.
*   **`page=1`**: Requests the first page of results.

In [4]:
response = requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=0afd6c2e672c77fc358fdbaa0d3d86a5&language=en-US&page=1')

This cell processes the API response and creates an initial pandas DataFrame:

*   **`response.json()`**: Parses the JSON content of the API response into a Python dictionary or list.
*   **`['results']`**: Accesses the list of movie data from the JSON response.
*   **`pd.DataFrame()`**: Converts this list of movie data into a pandas DataFrame.
*   **`[['id','title',...,'vote_count']]`**: Selects specific columns to include in the DataFrame, effectively filtering the raw API data.

In [9]:
temp_df = pd.DataFrame(response.json()['results'])[['id','title','overview','release_date','popularity','vote_average','vote_count']]

In [10]:
temp_df.head()

,id,title,overview,release_date,popularity,vote_average,vote_count
0,278,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,1994-09-23,48.8120,8.718,30059
1,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",1972-03-14,35.9986,8.687,22702
2,240,The Godfather Part II,In the continuing saga of the Corleone crime f...,1974-12-20,26.0517,8.572,13750
3,424,Schindler's List,The true story of how businessman Oskar Schind...,1993-12-15,24.4241,8.567,17278
4,389,12 Angry Men,The defense and the prosecution have rested an...,1957-04-10,20.7040,8.558,9869

This cell initializes an empty pandas DataFrame named `df`. This is often done when you plan to populate the DataFrame iteratively, for example, by concatenating data from multiple sources in a loop.

In [12]:
df = pd.DataFrame()

In [13]:
df

Empty DataFrame
Columns: []
Index: []

This crucial cell iterates through multiple pages of the TMDb API to collect a larger dataset:

*   **`for i in range(1,429)`**: Loops from page 1 up to (but not including) page 429.
*   **`requests.get(...)`**: Makes an API call for each page, dynamically inserting the page number `i` into the URL.
*   **`pd.DataFrame(...)`**: Creates a temporary DataFrame (`temprory_df`) for the results of each page.
*   **`pd.concat([df, temprory_df], ignore_index=True)`**: Appends the `temprory_df` from each page to the main `df` DataFrame. `ignore_index=True` ensures the new DataFrame has a continuous index rather than retaining the original indices from `df` and `temprory_df`.

In [16]:
for i in range(1,429):
  response = requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=0afd6c2e672c77fc358fdbaa0d3d86a5&language=en-US&page={}'.format(i))
  temprory_df = pd.DataFrame(response.json()['results'])[['id','title','overview','release_date','popularity','vote_average','vote_count']]
  df = pd.concat([df, temprory_df], ignore_index=True)

In [17]:
df

,id,title,overview,release_date,popularity,vote_average,vote_count
0,278,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,1994-09-23,48.8120,8.718,30059
1,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",1972-03-14,35.9986,8.687,22702
2,240,The Godfather Part II,In the continuing saga of the Corleone crime f...,1974-12-20,26.0517,8.572,13750
3,424,Schindler's List,The true story of how businessman Oskar Schind...,1993-12-15,24.4241,8.567,17278
4,389,12 Angry Men,The defense and the prosecution have rested an...,1957-04-10,20.7040,8.558,9869
...,...,...,...,...,...,...,...
8555,9894,The Cable Guy,When recently single Steven moves into his new...,1996-06-10,5.6618,5.995,2637
8556,9645,Ghost Ship,After discovering a passenger ship missing sin...,2002-10-25,5.9025,5.995,2625
8557,8555,Creep,"Trapped in a London subway station, a woman wh...",2004-08-10,2.4807,6.000,830
8558,1124620,The Monkey,When twin brothers find a mysterious wind-up m...,2025-02-14,11.4402,5.994,1249
8559,830788,The Invitation,"After the death of her mother, Evie is approac...",2022-08-24,3.4073,6.000,952

In [18]:
df.shape

(8560, 7)

The **`df.to_csv('movies.csv')`** function saves the entire `df` DataFrame to a CSV (Comma Separated Values) file named `movies.csv`. This allows you to persist the collected data for later use or sharing.

In [19]:
df.to_csv('movies.csv')